import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Header from '@/components/Header';
import Providers from './providers';
import { Toaster } from '@/components/ui/sonner';

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 950',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.className}`}>
        <Providers>
          <Header />
          <main className="max-w-[1200px] mx-auto w-full py-4 px-4">
            {children}
            <Toaster />
          </main>
        </Providers>
      </body>
    </html>
  );
}
