import SiteLayout from '@/components/SiteLayout';
import { Toaster } from '@/components/ui/sonner';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Providers from './providers';

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 950',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="overflow-y-scroll">
      <body className={`${pretendard.className} flex flex-col min-h-screen`}>
        <Providers>
          <SiteLayout>
            {children}
            <Toaster />
          </SiteLayout>
        </Providers>
      </body>
    </html>
  );
}
